### PR TITLE
[fix] readme links to `COLORTHEMES.md` and `CUSTOMPROMPTS.md`

### PR DESCRIPTION
**Pull request by plutonium-239**
This is pretty minor...

### CODE REVIEW

**Comment by chrisant996** [comment]
Oh, good catch, and thanks for making a PR.

Is that the right URL?  Wouldn't it need to start with `#` and use a relative path, like `#themes/WHATEVER.md`?

**Comment by plutonium-239** [comment]
I've always written URLs in github readmes like this (i.e. `/` = repo root), and they've worked well. 

Also, they were working in the preview, you can also check by clicking to edit it and then just previewing.

**Comment by chrisant996** [comment]
> I've always written URLs in github readmes like this (i.e. `/` = repo root), and they've worked well. 
> 
> Also, they were working in the preview, you can also check by clicking to edit it and then just previewing.

Ok sounds good!

**Comment by plutonium-239** [comment]
Just fyi, I found the [documentation](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#relative-links) which lists this behavior 😄

**Pull request merged**
